const PRODUCTS = [
  { id: '01', type: 'product', cat: 'access', tag: 'Access Control', img: 'assets/smart-lock.png', alt: 'Smart Lock', name: 'Smart Locks & Access Control', desc: 'Next-gen biometric and digital locking systems with multi-mode entry.', specs: ['Fingerprint recognition — up to 100 users', 'PIN code (4–8 digit programmable)', 'RFID / proximity card access', 'Bluetooth mobile app unlock'] },
  { id: '02', type: 'product', cat: 'surveillance', tag: 'Surveillance', img: 'assets/cctv.png', alt: 'CCTV Cameras', name: 'CCTV Surveillance Systems', desc: 'HD camera networks with intelligent monitoring, night vision & remote viewing.', specs: ['2MP / 4MP / 8MP (4K) resolution options', 'IR night vision up to 30m', 'Live remote viewing via app', 'Motion detection with instant alerts'] },
  { id: '03', type: 'product', cat: 'surveillance', tag: 'Alarm Systems', img: 'https://ajax.systems/wp-content/uploads/2020/09/keypad-plus-black-white-768x512.jpg', alt: 'Ajax Alarm Keypad', name: 'Alarm & Intrusion Detection', desc: 'Intelligent perimeter security with instant alerts for doors, windows & open spaces.', specs: ['Magnetic door/window contact sensors', 'PIR passive infrared motion detectors', 'GSM/GPRS SMS & call alert system', '110dB siren with strobe light'] },
  { id: '04', type: 'product', cat: 'automation', tag: 'Smart Home', img: 'https://www.home-on.com/wp-content/uploads/2021/04/Smart-Curtain-Motor-WIFI-Tuya.jpg', alt: 'Motorized Smart Curtains', name: 'Smart Curtain Systems', desc: 'Motorized, app-controlled curtain systems for privacy, comfort & energy efficiency.', specs: ['Quiet DC motor on motorized track', 'Wi-Fi remote control via smartphone app', 'Voice control (Alexa & Google Home)', 'Programmable open/close schedules'] },
  { id: '05', type: 'product', cat: 'power', tag: 'Solar Energy', img: 'assets/solar.jpg', alt: 'Monocrystalline Solar Panels', name: 'Solar Energy Solutions', desc: 'High-efficiency solar power for homes & businesses, with 24/7 battery backup.', specs: ['Monocrystalline panels — 300W to 550W', 'Lithium-ion battery backup banks', 'Pure sine wave inverters (1kVA–10kVA)', 'Remote monitoring via mobile app'] },
  { id: '06', type: 'product', cat: 'automation', tag: 'Gate Automation', img: 'assets/gate.jpg', alt: 'Centurion D3 Smart Gate Motor', name: 'Gate Automation Systems', desc: 'Reliable automatic swing and sliding gate systems for homes and businesses.', specs: ['Automatic swing gate operators', 'Sliding gate motor systems', 'Remote control & GSM intercom', 'Safety obstacle detection sensors'] },
  { id: '07', type: 'product', cat: 'access', tag: 'IP Telephony', img: 'assets/phone.png', alt: 'Yealink IP Business Phone', name: 'IP Phone Systems', desc: 'Scalable VoIP telephony solutions for businesses of all sizes.', specs: ['HD voice quality VoIP desk phones', 'Up to 1000+ extensions scalable', 'Auto-attendant & IVR system', 'Call recording & voicemail to email'] },
  { id: '08', type: 'product', cat: 'power', tag: 'Perimeter', img: 'https://www.nemtek.co.za/wp-content/uploads/2019/08/Nemtek-Wall-Top-Electric-Fence.jpg', alt: 'Nemtek Electric Fencing', name: 'Electric Fencing Systems', desc: 'High-voltage perimeter protection — the ultimate deterrent for intruders.', specs: ['Energiser output: 5kV to 10kV', 'Multi-zone detection & alarm', 'Lightning surge protection built-in', 'Remote monitoring & SMS alerts'] },
  { id: 'S01', type: 'service', cat: 'service', tag: 'Consultation', svg: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 20h9M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/></svg>', name: 'Security Site Survey', desc: 'Professional on-site assessment to identify vulnerabilities and design custom solutions.', specs: ['Comprehensive property audit', 'Risk and vulnerability assessment', 'System design blueprint', 'Detailed project cost estimation'] },
  { id: 'S02', type: 'service', cat: 'service', tag: 'Installation', svg: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m14.7 6.3-1.4-1.4a2 2 0 0 0-2.8 0L3.2 12.2a2 2 0 0 0 0 2.8l1.4 1.4M22 12l-4.6 4.6a2 2 0 0 1-2.8 0l-5.2-5.2a2 2 0 0 1 0-2.8L14 4"/></svg>', name: 'Full System Installation', desc: 'Expert installation of security hardware by certified EPICOM technicians.', specs: ['Clean cable routing and concealment', 'Configuration and calibration', 'System stress testing', 'Client handover & training'] },
  { id: 'S03', type: 'service', cat: 'service', tag: 'Maintenance', svg: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 9.36l-7.1 7.1a1 1 0 0 1-1.41-1.41l7.1-7.1a6 6 0 0 1 9.36-7.94z"/></svg>', name: 'Preventive Maintenance', desc: 'Annual or bi-annual maintenance contracts to keep your systems running flawlessly.', specs: ['Hardware cleaning & inspection', 'Firmware and software updates', 'Battery testing & replacement', 'Sensor calibration checks'] },
  { id: 'S04', type: 'service', cat: 'service', tag: 'Upgrade', svg: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>', name: 'System Upgrade', desc: 'Modernize legacy security systems with current generation smart technology.', specs: ['Analog to IP CCTV conversion', 'Smart home integration', 'Storage capacity expansion', 'Mobile app remote control setup'] },
  { id: 'S05', type: 'service', cat: 'service', tag: 'Support', svg: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>', name: '24/7 Remote Support', desc: 'Priority remote troubleshooting and technical support package.', specs: ['Dedicated support hotline', 'Remote system diagnostics', 'Configuration assistance', 'Emergency call-out priority'] }
];
